services:
  ai-rag-service-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-rag-service-manager
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root-token
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    restart: unless-stopped

    networks:
      - microservices-net

networks:
  microservices-net:
    external: true